# Generated by Django 6.0.2 on 2026-02-15 00:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=20)),
                ('time_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('min_fare', models.DecimalField(decimal_places=2, max_digits=20)),
                ('distance_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
