# Generated by Django 6.0.2 on 2026-02-15 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceconfig',
            name='time_price',
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_location_name', models.CharField(max_length=225)),
                ('dropoff_location_name', models.CharField(max_length=225)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=20)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=20)),
                ('dropoff_lng', models.DecimalField(decimal_places=6, max_digits=20)),
                ('dropoff_lat', models.DecimalField(decimal_places=6, max_digits=20)),
                ('total_distance', models.DecimalField(decimal_places=6, max_digits=20)),
                ('final_fare', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('SEARCHING', 'Looking for a keke'), ('ACCEPTED', 'Driver is on the way'), ('STARTED', 'Passenger is in the keke'), ('COMPLETED', 'Ride finished'), ('CANCELLED', 'Someone gave up')], default='SEARCHING', max_length=225)),
                ('otp', models.CharField(max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.driverprofile')),
                ('price_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.priceconfig')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.riderprofile')),
            ],
        ),
    ]
