# Generated by Django 6.0.2 on 2026-02-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_driverprofile_is_active_and_more'),
        ('rides', '0002_remove_priceconfig_time_price_trips'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='rejected_trips', to='accounts.driverprofile'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='status',
            field=models.CharField(choices=[('SEARCHING', 'Looking for a keke'), ('ACCEPTED', 'Driver is on the way'), ('STARTED', 'Passenger is in the keke'), ('COMPLETED', 'Ride finished'), ('CANCELLED', 'Someone gave up'), ('REJECTED', 'The driver rejected the trip')], default='SEARCHING', max_length=225),
        ),
    ]
