# Generated by Django 6.0.2 on 2026-03-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_trips_rejected_by_alter_trips_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
