# Generated by Django 6.0.2 on 2026-08-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_trips_driver_lat_trips_driver_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='passenger_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='passenger_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
