# Generated by Django 6.0.2 on 2026-08-21 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_add_passenger_coords'),
        ('rides', '0007_trips_passenger_lat_trips_passenger_lng'),
    ]

    operations = [
    ]
