[project]
name = "reikeke-backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "Django==6.0.1",
    "psycopg2-binary",
    "dj-database-url",
    "djangorestframework",
    "djangorestframework-simplejwt",
    "django-cors-headers",
    "python-dotenv",
    "whitenoise",
    "channels",
    "requests",
    "channels-redis",
    "daphne",
    "redis",
]

[tool.vercel.scripts]
# uv run ensures the commands are executed inside the environment where Django is installed
build = "uv run python manage.py migrate --noinput && uv run python manage.py collectstatic --noinput --clear"

[tool.vercel]
entrypoint = "backend.wsgi:application"